attributes:
    homebrewalt:
        apps:
            - git
            - youtube-dl
        cask_apps:
            - google-chrome
            - android-file-transfer
            - audacity
            - box-sync
            - caffeine
            - chicken
            - disk-inventory-x
            - dropbox
            - firefox
            - fluid
            - google-chrome
            - google-drive
            - growl-fork
            - kindle
            - send-to-kindle
            - libreoffice
            - pokerstars
            - scroll-reverser
            - sizeup
            - skype
            - slack
            - soundflower
            - spotify
            - steam
            - teamviewer
            - textmate
            - the-unarchiver
            - thunderbird
            - torbrowserbundle
            - transmission
            - vlc
            - cd-to
            - iterm2
            - nvalt
            - teleport
            #- fuze #still waiting for pull request to be accepted